name: deploy
on:
  push:
    branches:
      - feature/test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: "1.17"

      - uses: actions/checkout@v2.4.0

      - run: go build server.go

      - name: deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          echo "${PRIVATE_KEY}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "kill -9 `lsof -i:8080 | grep server | awk '{print $2}'` 2>/dev/null; ./server &"
